server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      security:
        enabled: false
      plugin:
        config:
          log-request: false
          read-request-data: true
          read-response-data: false
      routes:
        - id: rent
          uri: lb://rent-image
          predicates:
            - Path=/api/rent/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@customKeyResolver}'
                redis-rate-limiter.replenishRate: 40
                redis-rate-limiter.burstCapacity: 80
            - RewritePath=/api/(?<rent>.*), /$\{rent}
            - AddResponseHeader=X-Some-Header, gateway-header

        - id: price
          uri: lb://price-image
          predicates:
            - Path=/api/price/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@customKeyResolver}'
                redis-rate-limiter.replenishRate: 40
                redis-rate-limiter.burstCapacity: 80
            - RewritePath=/api/(?<price>.*), /$\{price}

        - id: audit
          uri: lb://audit-image
          predicates:
            - Path=/api/audit/**
          filters:
            - RewritePath=/api/(?<audit>.*), /$\{audit}    

        - id: forms
          uri: lb://platform-forms
          predicates:
            - Path=/api/forms/**
            - Path=/api/{version}/forms/**
          filters:
            - RewritePath=/api/forms/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/forms/tasks/(?<path>.*), /$\{version}/tasks/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: tree
          uri: lb://platform-tree
          predicates:
            - Path=/api/{version}/tree/**
          filters:
            - RewritePath=/api/(?<path>.*), /$\{path}
            


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

jwt:
  serviceIds:
    gateway-application: "bb743523-f390-4a08-834e-9d1c592ccec4"
