server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      plugin:
        config:
          log-request: false
          read-request-data: true
          read-response-data: false
      routes:      
        - id: tree
          uri: lb://platform-tree
          predicates:
            - Path=/api/{version}/tree/**, /api/tree/**
          filters:
            - RewritePath=/api/tree/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/tree/abac/(?<path>.*), /$\{version}/abac/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: mdm
          uri: lb://platform-mdm
          predicates:
            - Path=/api/{version}/mdm/**, /api/mdm/**
          filters:
            - RewritePath=/api/mdm/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/mdm/abac/(?<path>.*), /$\{version}/abac/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: math
          uri: lb://platform-math
          predicates:
            - Path=/api/{version}/math/**, /api/math/**
          filters:
            - RewritePath=/api/math/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/math/abac/(?<path>.*), /$\{version}/abac/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: forms
          uri: lb://platform-forms
          predicates:
            - Path=/api/{version}/forms/**, /api/forms/**
          filters:
            - RewritePath=/api/forms/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/forms/abac/(?<path>.*), /$\{version}/abac/$\{path}
            - RewritePath=/api/(?<version>.*)/forms/tasks/(?<path>.*), /$\{version}/tasks/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: validation
          uri: lb://platform-validation
          predicates:
            - Path=/api/{version}/validation/**, /api/validation/**
          filters:
            - RewritePath=/api/validation/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/validation/abac/(?<path>.*), /$\{version}/abac/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: identity
          uri: lb://platform-identity
          predicates:
            - Path=/api/{version}/identity/**, /api/identity/**
          filters:
            - RewritePath=/api/identity/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/identity/abac/(?<path>.*), /$\{version}/abac/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: file
          uri: lb://platform-file
          predicates:
            - Path=/api/{version}/file/**, /api/file/**
          filters:
            - RewritePath=/api/file/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<version>.*)/file/abac/(?<path>.*), /$\{version}/abac/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

        - id: mockserver
          uri: http://mockserver:1080
          predicates:
            - Path=/api/{version}/mockserver/**, /api/mockserver/**
          filters:
            - RewritePath=/api/v1/mockserver/(?<path>.*), /$\{path}

        - id: policy
          uri: lb://platform-policy
          predicates:
            - Path=/api/{version}/abac/**, /api/abac/**
          filters:
            - RewritePath=/api/abac/actuator/(?<path>.*), /actuator/$\{path}
            - RewritePath=/api/(?<path>.*), /$\{path}

gateway:
  security:
    enabled: true
    key-life-time: 15m
    key-usage-time: 10m
    inactivity-time: 30m
    force-single-session: false
    force-global-logout: false
  services:
    - platform-file
    - platform-forms
    - platform-gateway
    - platform-identity
    - platform-math
    - platform-mdm
    - platform-tree
    - platform-validation

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000