server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: rent
          uri: lb://rent-image
          predicates:
            - Path=/api/rent/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@customKeyResolver}'
                redis-rate-limiter.replenishRate: 40
                redis-rate-limiter.burstCapacity: 80
            - RewritePath=/api/(?<rent>.*), /$\{rent}
            - AddResponseHeader=X-Some-Header, gateway-header

        - id: price
          uri: lb://price-image
          predicates:
            - Path=/api/price/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@customKeyResolver}'
                redis-rate-limiter.replenishRate: 40
                redis-rate-limiter.burstCapacity: 80
            - RewritePath=/api/(?<price>.*), /$\{price}

        - id: audit
          uri: lb://audit-image
          predicates:
            - Path=/api/audit/**
          filters:
            - RewritePath=/api/(?<audit>.*), /$\{audit}    

        - id: forms
          uri: lb://platform-forms-image
          predicates:
            - Path=/api/v1/forms/**
          filters:
            - RewritePath=/api/v1/forms/(?<path>.*), /v1/forms/$\{path}


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
