spring:
  jackson:
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin-9411/
    discovery-client-enabled: true
    sender:
      type: web
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://188.127.226.180:15432/mdm-form
    username: postgres
    password: postgres
    hikari:
      schema: "public"
      minimum-idle: 2
      maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
