spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://188.127.226.180:25432/mdm-identity?ApplicationName=local-identity-omelyanov
    username: postgres
    password: AceTate1221!
    hikari:
      schema: "public"
      minimum-idle: 2
      maximum-pool-size: 10
      maxLifetime: 600000

