spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://188.127.226.180:15432/mdm-form?ApplicationName=local-forms-omelyanov
    username: postgres
    password: AceTate1221!
    hikari:
      schema: "public"
      minimum-idle: 2
      maximum-pool-size: 10

task:
  concurrency:
    import_queue: 3
    export_queue: 3
