server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: full

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - com.gostgroup.platform.template.infrastructure.exception.BusinessException
    shared:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 100
      ringBufferSizeInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - com.gostgroup.platform.template.infrastructure.exception.BusinessException
  instances:
    rentService:
      baseConfig: default
      ringBufferSizeInClosedState: 5

